### PR TITLE
feat add toggle button to force activate deactivate

### PR DESCRIPTION
**Pull request by damieng57**
Add a button in the navigation to active/desactive magic-json on current file.
It's based on my previous branch: feat/dg/add-toggle-button-to-force-activate-deactivate

### CODE REVIEW

**Comment by Odonno** [comment]
Hello @damieng57 

I merged your previous PR. Can you rebase so that we can have a clear view of what's changed?
Note that I migrated to `bun`, so there may be some conflicts on the `package.json` file, scripts updated and indentation is different.

Other than that, can you share a gif to see what this PR will provide?

**Comment by damieng57** [comment]
I added your last changes and update features.gif

**Comment by Odonno** [comment]
Wow, that looks really good. Thank you for your efforts @damieng57

**Comment by Odonno** [comment]
v1.0.3 is now published

**Pull request merged**
